"""
XLSX Exporter v3 — Professional data report with Swiss International design.
6 sheets: Executive Summary, Modules, SOP Workflow, KPI Dashboard, Risk Matrix, Analysis.
Styled with proper headers, alternating rows, conditional formatting, and chart data.
"""
from __future__ import annotations
import os as _os, uuid as _uuid

def _parse_target(t):
    if not t: return (None, None)
    import re
    m = re.match(r'[>=<]+\s*([\d.]+)\s*%?', str(t))
    if m: return (float(m.group(1)), '%' in str(t))
    try: return (float(t), False)
    except: return (None, None)

def export_xlsx(business_system, output_path=None):
    """Generate professional 6-sheet Excel workbook from Business System JSON."""
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side, numbers
        from openpyxl.utils import get_column_letter
    except ImportError:
        raise ImportError("openpyxl required: pip install openpyxl")

    wb = Workbook()
    bs = business_system.get('business_system', business_system)

    # === DESIGN TOKENS ===
    INK = "0A0A0A"
    ACCENT = "002FA7"
    PAPER = "FAFAF8"
    GREY1 = "F0F0EE"
    GREY2 = "D4D4D2"
    GREEN = "22C55E"
    RED = "DC2626"
    ORANGE = "F97316"

    hdr_font = Font(name='Inter', bold=True, size=11, color=INK)
    title_font = Font(name='Inter', bold=True, size=14, color=ACCENT)
    body_font = Font(name='Inter', size=10, color=INK)
    mono_font = Font(name='JetBrains Mono', size=9, color="525252")
    hdr_fill = PatternFill(start_color=GREY1, end_color=GREY1, fill_type='solid')
    accent_fill = PatternFill(start_color=ACCENT, end_color=ACCENT, fill_type='solid')
    green_fill = PatternFill(start_color=GREEN, end_color=GREEN, fill_type='solid')
    red_fill = PatternFill(start_color=RED, end_color=RED, fill_type='solid')
    orange_fill = PatternFill(start_color=ORANGE, end_color=ORANGE, fill_type='solid')
    thin_border = Border(
        left=Side(style='thin', color=GREY2),
        right=Side(style='thin', color=GREY2),
        top=Side(style='thin', color=GREY2),
        bottom=Side(style='thin', color=GREY2),
    )
    center = Alignment(horizontal='center', vertical='center', wrap_text=True)
    left = Alignment(horizontal='left', vertical='center', wrap_text=True)

    def style_header(ws, row, cols):
        for c in range(1, cols+1):
            cell = ws.cell(row=row, column=c)
            cell.font = hdr_font
            cell.fill = hdr_fill
            cell.alignment = center
            cell.border = thin_border

    def style_row(ws, row, cols, alt=False):
        for c in range(1, cols+1):
            cell = ws.cell(row=row, column=c)
            cell.font = body_font
            cell.alignment = left if c == 1 else center
            cell.border = thin_border
            if alt:
                cell.fill = PatternFill(start_color=PAPER, end_color=PAPER, fill_type='solid')

    def auto_width(ws, cols, max_w=55):
        for c in range(1, cols+1):
            ws.column_dimensions[get_column_letter(c)].width = min(max_w, 18 if c == 1 else 30)

    # ============ SHEET 1: Executive Summary ============
    ws1 = wb.active
    ws1.title = "Executive Summary"
    ws1.sheet_properties.tabColor = ACCENT
    ws1.merge_cells('A1:C1')
    ws1.cell(row=1, column=1, value="Business System Report").font = title_font
    ws1.cell(row=2, column=1, value="Generated by SOP Insight Engine").font = Font(name='Inter', size=9, color="737373", italic=True)
    modules = bs.get('modules') or []
    if isinstance(modules, dict):
        modules = [modules]
    ws1.cell(row=4, column=1, value="Business Modules").font = hdr_font
    style_header(ws1, 4, 3)
    ws1.cell(row=4, column=2, value="Description")
    ws1.cell(row=4, column=3, value="Owner")
    for i, m in enumerate(modules[:20]):
        r = 5 + i
        ws1.cell(row=r, column=1, value=m.get('name', ''))
        ws1.cell(row=r, column=2, value=m.get('description', ''))
        ws1.cell(row=r, column=3, value=m.get('owner', '-'))
        style_row(ws1, r, 3, i%2==0)
    auto_width(ws1, 3)

    # ============ SHEET 2: Modules ============
    ws2 = wb.create_sheet("Modules")
    ws2.sheet_properties.tabColor = ACCENT
    ws2.merge_cells('A1:D1')
    ws2.cell(row=1, column=1, value="Module Breakdown").font = title_font
    ws2.cell(row=3, column=1, value="Module").font = hdr_font
    ws2.cell(row=3, column=2, value="Description").font = hdr_font
    ws2.cell(row=3, column=3, value="Owner").font = hdr_font
    ws2.cell(row=3, column=4, value="Dependencies").font = hdr_font
    style_header(ws2, 3, 4)
    for i, m in enumerate(modules[:30]):
        r = 4 + i
        ws2.cell(row=r, column=1, value=m.get('name', ''))
        ws2.cell(row=r, column=2, value=m.get('description', ''))
        ws2.cell(row=r, column=3, value=m.get('owner', '-'))
        # Current schema: dependencies is list of ModuleDependency objects with 'module_name' field
        deps = m.get('dependencies', [])
        if deps and isinstance(deps, list):
            dep_names = [d.get('module_name', str(d)) if isinstance(d, dict) else str(d) for d in deps]
            ws2.cell(row=r, column=4, value=', '.join(dep_names) if dep_names else '-')
        else:
            ws2.cell(row=r, column=4, value='-')
        style_row(ws2, r, 4, i%2==0)
    auto_width(ws2, 4, 40)

    # ============ SHEET 3: SOP Workflow ============
    ws3 = wb.create_sheet("SOP Workflow")
    ws3.sheet_properties.tabColor = "5A9E96"
    ws3.merge_cells('A1:E1')
    ws3.cell(row=1, column=1, value="SOP Workflow Process").font = title_font
    ws3.cell(row=3, column=1, value="Step").font = hdr_font
    ws3.cell(row=3, column=2, value="Owner").font = hdr_font
    ws3.cell(row=3, column=3, value="Next Step(s)").font = hdr_font
    ws3.cell(row=3, column=4, value="SLA").font = hdr_font
    ws3.cell(row=3, column=5, value="Risk Level").font = hdr_font
    style_header(ws3, 3, 5)
    workflow = bs.get('workflow', [])
    # Map risk.affected_nodes -> impact for the workflow sheet (current schema)
    risks_by_node = {}
    for r in (bs.get('risks') or []):
        if not isinstance(r, dict):
            continue
        impact = r.get('impact', r.get('severity', 'low'))
        for node_id in (r.get('affected_nodes') or []):
            risks_by_node[node_id] = impact
    for i, w in enumerate(workflow[:40]):
        r = 4 + i
        step_name = w.get('name', w.get('id', ''))
        ws3.cell(row=r, column=1, value=step_name)
        ws3.cell(row=r, column=2, value=w.get('owner', '-'))
        # Build next-step label from next_node_id + conditions (current schema)
        next_parts = []
        if w.get('next_node_id'):
            next_parts.append(w['next_node_id'])
        for cond in (w.get('conditions') or []):
            next_parts.append(f"{cond.get('condition','')}→{cond.get('next_node_id','')}")
        ws3.cell(row=r, column=3, value=', '.join(next_parts) if next_parts else '-')
        sla = w.get('sla_hours', w.get('sla', '-'))
        ws3.cell(row=r, column=4, value=f"{sla}h" if sla not in (None, '-', '') else '-')
        risk_level = risks_by_node.get(w.get('id', ''), 'low')
        risk_cell = ws3.cell(row=r, column=5, value=risk_level.upper())
        if risk_level == 'high': risk_cell.fill = red_fill; risk_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        elif risk_level == 'medium': risk_cell.fill = orange_fill; risk_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        else: risk_cell.fill = green_fill; risk_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        risk_cell.alignment = center
        style_row(ws3, r, 5, i%2==0)
    auto_width(ws3, 5)

    # ============ SHEET 4: KPI Dashboard ============
    ws4 = wb.create_sheet("KPI Dashboard")
    ws4.sheet_properties.tabColor = "C9A84C"
    ws4.merge_cells('A1:F1')
    ws4.cell(row=1, column=1, value="KPI Metrics Dashboard").font = title_font
    ws4.cell(row=3, column=1, value="KPI Name").font = hdr_font
    ws4.cell(row=3, column=2, value="Formula").font = hdr_font
    ws4.cell(row=3, column=3, value="Target").font = hdr_font
    ws4.cell(row=3, column=4, value="Current").font = hdr_font
    ws4.cell(row=3, column=5, value="Status").font = hdr_font
    ws4.cell(row=3, column=6, value="Trend").font = hdr_font
    style_header(ws4, 3, 6)
    # Current schema: metrics list + kpi tree structure
    kpis = bs.get('metrics', [])
    if not kpis and isinstance(bs.get('kpi'), list):
        kpis = bs.get('kpi', [])
    for i, k in enumerate(kpis[:30]):
        r = 4 + i
        ws4.cell(row=r, column=1, value=k.get('name', ''))
        ws4.cell(row=r, column=2, value=k.get('formula', '-'))
        target = k.get('target', '-')
        ws4.cell(row=r, column=3, value=target)
        current = k.get('current', k.get('value', '-'))
        ws4.cell(row=r, column=4, value=current)
        t_val, is_pct = _parse_target(target)
        status = 'PASS'
        if t_val is not None and isinstance(current, (int, float)):
            if is_pct:
                status = 'PASS' if current >= t_val else 'WARN' if current >= t_val * 0.9 else 'FAIL'
        status_cell = ws4.cell(row=r, column=5, value=status)
        if status == 'PASS': status_cell.fill = green_fill; status_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        elif status == 'WARN': status_cell.fill = orange_fill; status_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        else: status_cell.fill = red_fill; status_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        status_cell.alignment = center
        trend = k.get('trend', [])
        ws4.cell(row=r, column=6, value=' → '.join(str(round(v,1)) for v in trend[-6:]) if trend else '-')
        style_row(ws4, r, 6, i%2==0)
    auto_width(ws4, 6)

    # ============ SHEET 5: Risk Matrix ============
    ws5 = wb.create_sheet("Risk Matrix")
    ws5.sheet_properties.tabColor = "C0392B"
    ws5.merge_cells('A1:E1')
    ws5.cell(row=1, column=1, value="Risk Analysis Matrix").font = title_font
    ws5.cell(row=3, column=1, value="Risk").font = hdr_font
    ws5.cell(row=3, column=2, value="Related Step").font = hdr_font
    ws5.cell(row=3, column=3, value="Impact").font = hdr_font
    ws5.cell(row=3, column=4, value="Probability").font = hdr_font
    ws5.cell(row=3, column=5, value="Mitigation").font = hdr_font
    style_header(ws5, 3, 5)
    risk_items = bs.get('risks') or bs.get('risk') or []
    if isinstance(risk_items, dict):
        risk_items = [risk_items]
    for i, rk in enumerate(risk_items[:30]):
        r = 4 + i
        ws5.cell(row=r, column=1, value=rk.get('name', ''))
        # Current schema: affected_nodes list, not related_step single
        affected = rk.get('affected_nodes', [])
        ws5.cell(row=r, column=2, value=', '.join(affected) if affected else '-')
        impact = rk.get('impact', 'medium')
        impact_cell = ws5.cell(row=r, column=3, value=impact.upper())
        if impact == 'high': impact_cell.fill = red_fill; impact_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        elif impact == 'medium': impact_cell.fill = orange_fill; impact_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        else: impact_cell.fill = green_fill; impact_cell.font = Font(name='Inter', bold=True, size=9, color='FFFFFF')
        impact_cell.alignment = center
        ws5.cell(row=r, column=4, value=rk.get('probability', 'unknown'))
        # Current schema: mitigation may be a string or an object with 'action'
        mit = rk.get('mitigation', '')
        if isinstance(mit, str):
            mit_text = mit
        elif isinstance(mit, dict):
            mit_text = mit.get('action', '-')
        else:
            mit_text = '-'
        ws5.cell(row=r, column=5, value=mit_text)
        style_row(ws5, r, 5, i%2==0)
    auto_width(ws5, 5, 40)

    # ============ SHEET 6: Analysis & Recommendations ============
    ws6 = wb.create_sheet("Analysis")
    ws6.sheet_properties.tabColor = "525252"
    ws6.merge_cells('A1:B1')
    ws6.cell(row=1, column=1, value="Analysis & Recommendations").font = title_font

    # Summary stats
    ws6.cell(row=3, column=1, value="Metric").font = hdr_font
    ws6.cell(row=3, column=2, value="Value").font = hdr_font
    style_header(ws6, 3, 2)
    stats = [
        ("Total Modules", len(modules)),
        ("Total Workflow Steps", len(workflow)),
        ("Total KPIs", len(kpis)),
        ("Total Risks", len(risk_items)),
        ("High Impact Risks", sum(1 for r in risk_items if r.get('impact') == 'high')),
        ("Medium Impact Risks", sum(1 for r in risk_items if r.get('impact') == 'medium')),
        ("KPI Pass Rate", f"{sum(1 for k in kpis if k.get('status','')=='pass')}/{len(kpis)}" if kpis else "N/A"),
    ]
    for i, (label, val) in enumerate(stats):
        r = 4 + i
        ws6.cell(row=r, column=1, value=label)
        ws6.cell(row=r, column=2, value=str(val))
        style_row(ws6, r, 2, i%2==0)

    # Recommendations
    ws6.cell(row=13, column=1, value="Recommendations").font = hdr_font
    recs = [
        "Monitor high-impact risks with automated alerts",
        "Review KPI targets quarterly against actual performance",
        "Automate repetitive workflow steps where ROI > 2x",
        "Conduct quarterly risk review with stakeholders",
        "Cross-reference industry benchmarks for KPI targets",
    ]
    for i, rec in enumerate(recs):
        ws6.cell(row=14+i, column=1, value=rec).font = body_font
        ws6.merge_cells(start_row=14+i, start_column=1, end_row=14+i, end_column=2)
    auto_width(ws6, 2, 60)

    # Save
    if output_path is None:
        output_path = _os.path.join(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))), 'output', f'bsc_report_{_uuid.uuid4().hex[:12]}.xlsx')
    _os.makedirs(_os.path.dirname(output_path), exist_ok=True)
    wb.save(output_path)
    return output_path
