"""
Validator Rules - 4 focused business rules for JSON repair.

Each rule is standalone:
  rule_1: if modules == [] -> inject default module
  rule_2: if workflow disconnected -> rebuild edges
  rule_3: if kpi missing formula -> generate formula
  rule_4: if risk not mapped -> assign nearest workflow step

Returns (fixed: bool, detail: str). Modifies data in-place.
"""

from collections import deque
from typing import Callable

DEFAULT_MODULE = {
    "id": "mod-default", "name": "Core Business Module",
    "description": "Primary business module auto-generated by validator.",
    "owner": "System", "priority": "high",
}

FORMULA_PATTERNS = {
    "throughput": "items_processed / time_unit",
    "volume": "count / time_unit",
    "error": "(errors / total) * 100",
    "accuracy": "(correct / total) * 100",
    "precision": "(true_positives / (true_positives + false_positives)) * 100",
    "time": "sum(processing_time) / count",
    "duration": "sum(duration) / count",
    "cycle": "sum(cycle_time) / count",
    "latency": "avg(response_time)",
    "cost": "total_cost / units",
    "queue": "count(pending_items)",
    "backlog": "count(pending_items)",
    "rate": "(events / total) * 100",
    "ratio": "(numerator / denominator) * 100",
    "sla": "(compliant / total) * 100",
    "compliance": "(compliant / total) * 100",
    "satisfaction": "sum(scores) / count",
    "csat": "sum(scores) / count",
    "utilization": "(busy_time / available_time) * 100",
    "availability": "(uptime / total_time) * 100",
    "conversion": "(conversions / visitors) * 100",
}


# ============================================================
# RULE 1
# ============================================================

def rule_modules_not_empty(data: dict) -> tuple:
    """If modules list is empty or missing, inject a default module."""
    modules = data.get("modules")
    if modules is None:
        data["modules"] = [dict(DEFAULT_MODULE)]
        return True, "modules was None -> injected 1 default module"
    if not isinstance(modules, list):
        data["modules"] = [dict(DEFAULT_MODULE)]
        return True, "modules was not a list -> replaced with 1 default module"
    if len(modules) == 0:
        data["modules"].append(dict(DEFAULT_MODULE))
        return True, "modules was empty -> injected 1 default module"
    return False, "modules OK"


# ============================================================
# RULE 2
# ============================================================

def rule_workflow_connected(data: dict) -> tuple:
    """If workflow disconnected, rebuild edges. BFS from start, bridge unreachable."""
    workflow = data.get("workflow")
    pre_fixes = 0  # structural fixes before BFS

    if not workflow or not isinstance(workflow, list) or len(workflow) == 0:
        data["workflow"] = [
            {"id": "start", "name": "Start", "type": "start", "owner": "User", "next_node_id": "end"},
            {"id": "end", "name": "Complete", "type": "end", "owner": "System"},
        ]
        return True, "workflow was empty -> injected start+end"

    for i, node in enumerate(workflow):
        if not isinstance(node, dict):
            workflow[i] = {"id": "step-%d" % (i+1), "name": "Step %d" % (i+1), "type": "action", "owner": "unassigned"}
            pre_fixes += 1
        if not node.get("id"):
            node["id"] = "step-%d" % (i+1)
            pre_fixes += 1
        node.setdefault("name", node["id"].replace("-", " ").title())
        node.setdefault("type", "action")
        node.setdefault("owner", "unassigned")

    node_ids = {n["id"] for n in workflow}
    has_start = any(n.get("type") == "start" for n in workflow)
    has_end = any(n.get("type") == "end" for n in workflow)

    if not has_start:
        workflow[0]["type"] = "start"
        pre_fixes += 1
    if not has_end:
        if len(workflow) == 1:
            workflow.append({"id": "end", "name": "Complete", "type": "end", "owner": "System"})
            workflow[0]["next_node_id"] = "end"
            node_ids.add("end")
            pre_fixes += 2  # added node + edge
        else:
            workflow[-1]["type"] = "end"
            workflow[-1].pop("next_node_id", None)
            workflow[-1].pop("conditions", None)
            pre_fixes += 1

    adj = {nid: [] for nid in node_ids}
    for node in workflow:
        nid = node["id"]
        if node.get("next_node_id") and node["next_node_id"] in node_ids:
            adj[nid].append(node["next_node_id"])
        for cond in node.get("conditions", []):
            cid = cond.get("next_node_id", "")
            if cid in node_ids:
                adj[nid].append(cid)

    start_ids = [n["id"] for n in workflow if n.get("type") == "start"]
    reachable = set()
    queue = deque(start_ids)
    while queue:
        cur = queue.popleft()
        if cur not in reachable:
            reachable.add(cur)
            for nb in adj.get(cur, []):
                if nb not in reachable:
                    queue.append(nb)

    unreachable = node_ids - reachable
    end_ids = [n["id"] for n in workflow if n.get("type") == "end"]
    bfs_fixes = 0

    if unreachable and reachable:
        bridge = next(iter(reachable))
        for uid in unreachable:
            bn = next((n for n in workflow if n["id"] == bridge), None)
            if bn:
                bn.setdefault("conditions", [])
                bn["conditions"].append({"condition": "repaired", "next_node_id": uid})
                bn.pop("next_node_id", None)
                bfs_fixes += 1
    elif unreachable and start_ids:
        chain = list(unreachable)
        for j, nid in enumerate(chain[:-1]):
            node = next((n for n in workflow if n["id"] == nid), None)
            if node:
                node["next_node_id"] = chain[j+1]
                node.pop("conditions", None)
                bfs_fixes += 1
        if chain and end_ids:
            last = next((n for n in workflow if n["id"] == chain[-1]), None)
            if last:
                last["next_node_id"] = end_ids[0]
                bfs_fixes += 1

    for node in workflow:
        if node.get("type") == "end":
            continue
        has_out = bool(node.get("next_node_id")) or bool(node.get("conditions"))
        if not has_out and end_ids:
            node["next_node_id"] = end_ids[0]
            bfs_fixes += 1

    total_fixes = pre_fixes + bfs_fixes
    if total_fixes > 0:
        return True, "rebuilt %d edges (pre=%d bfs=%d, %d unreachable)" % (total_fixes, pre_fixes, bfs_fixes, len(unreachable))
    return False, "workflow connected (%d nodes)" % len(workflow)

# ============================================================
# RULE 3
# ============================================================

def _gen_formula(name: str) -> str:
    lower = name.lower()
    for kw, fm in FORMULA_PATTERNS.items():
        if kw in lower:
            return fm
    return "metric_value_measured"


def rule_kpi_has_formula(data: dict) -> tuple:
    """If any KPI missing a formula, generate one based on its name."""
    metrics = list(data.get("metrics", []) or [])
    kpi_list = data.get("kpi", []) or []
    if isinstance(kpi_list, list) and kpi_list:
        metrics.extend(kpi_list)
    if not metrics:
        return False, "no metrics to check"

    fixed = 0
    for i, metric in enumerate(metrics):
        if not isinstance(metric, dict):
            continue
        formula = metric.get("formula")
        if formula and str(formula).strip() not in ("", "TBD", "None", "none"):
            continue
        name = metric.get("name", "Metric %d" % (i+1))
        metric["formula"] = _gen_formula(name)
        fixed += 1

    if fixed > 0:
        return True, "generated formulas for %d metrics" % fixed
    return False, "all %d metrics have formulas" % len(metrics)


# ============================================================
# RULE 4
# ============================================================

def rule_risk_mapped(data: dict) -> tuple:
    """If risk not mapped to workflow, assign nearest workflow step."""
    risks = data.get("risk", []) or []
    if not isinstance(risks, list) or not risks:
        return False, "no risks to map"

    workflow = data.get("workflow", []) or []
    wf_ids = [
        n["id"] for n in workflow
        if isinstance(n, dict) and n.get("id")
        and n.get("type") not in ("start", "end")
    ]
    if not wf_ids:
        wf_ids = [n["id"] for n in workflow if isinstance(n, dict) and n.get("id")]

    mapped = 0
    for i, risk in enumerate(risks):
        if not isinstance(risk, dict):
            continue
        affected = risk.get("affected_nodes") or risk.get("affected_steps") or []
        related = risk.get("related_step", "")
        if (isinstance(affected, list) and len(affected) > 0) or related:
            continue
        if wf_ids:
            idx = i % len(wf_ids)
            risk["affected_nodes"] = [wf_ids[idx]]
            if not related:
                risk["related_step"] = wf_ids[idx]
        else:
            risk["affected_nodes"] = ["unknown"]
        mapped += 1

    if mapped > 0:
        return True, "mapped %d risks to workflow steps" % mapped
    return False, "all %d risks already mapped" % len(risks)


# ============================================================
# RUN ALL
# ============================================================

ALL_RULES = [
    ("rule_modules_not_empty", rule_modules_not_empty),
    ("rule_workflow_connected", rule_workflow_connected),
    ("rule_kpi_has_formula", rule_kpi_has_formula),
    ("rule_risk_mapped", rule_risk_mapped),
]


def validate_all(data: dict) -> dict:
    results = []
    any_fixed = False
    for name, fn in ALL_RULES:
        fixed, detail = fn(data)
        results.append({"name": name, "fixed": fixed, "detail": detail})
        if fixed:
            any_fixed = True
    return {
        "fixed": any_fixed,
        "rules_applied": sum(1 for r in results if r["fixed"]),
        "rules": results,
    }


# ============================================================
# TEST
# ============================================================
if __name__ == "__main__":
    print("=== Rule 1: empty modules ===")
    d1 = {"modules": []}
    f, det = rule_modules_not_empty(d1)
    assert f and len(d1["modules"]) == 1, det
    print("  OK:", det)

    print("=== Rule 2: disconnected workflow ===")
    d2 = {"workflow": [{"id": "orphan", "type": "action", "owner": "X"}]}
    f, det = rule_workflow_connected(d2)
    assert f, det
    nodes = d2["workflow"]
    assert any(n["type"] == "start" for n in nodes)
    assert any(n["type"] == "end" for n in nodes)
    print("  OK:", det)

    print("=== Rule 3: missing formula ===")
    d3 = {"metrics": [
        {"name": "Throughput", "formula": ""},
        {"name": "Error Rate"},
        {"name": "CSAT", "formula": "TBD"},
    ]}
    f, det = rule_kpi_has_formula(d3)
    assert f, det
    for m in d3["metrics"]:
        assert m["formula"] not in ("", "TBD"), m["name"]
    print("  OK:", det)

    print("=== Rule 4: unmapped risk ===")
    d4 = {
        "workflow": [
            {"id": "validate", "type": "action", "owner": "Sys"},
            {"id": "process", "type": "action", "owner": "Eng"},
        ],
        "risk": [
            {"name": "Risk A", "affected_nodes": []},
            {"name": "Risk B"},
            {"name": "Risk C", "affected_nodes": ["validate"]},
        ]
    }
    f, det = rule_risk_mapped(d4)
    assert f and len(d4["risk"][0]["affected_nodes"]) > 0, det
    print("  OK:", det)

    print("=== All Rules ===")
    d5 = {"modules": [], "workflow": [], "metrics": [], "risk": []}
    rpt = validate_all(d5)
    print("  fixed=%s applied=%d" % (rpt["fixed"], rpt["rules_applied"]))
    for r in rpt["rules"]:
        print("    [%s] %s: %s" % (r["fixed"], r["name"], r["detail"]))
    print("\nAll tests passed!")
