import { ThemeType, ThemeConfig } from '../types';

export const themes: Record<ThemeType, ThemeConfig> = {
  business: {
    name: '商务',
    primary: '#1e3a5f',
    secondary: '#0ea5e9',
    background: '#ffffff',
    text: '#1f2937',
    textLight: '#6b7280',
    textFaint: '#9ca3af',
    accent: '#3b82f6',
    success: '#22c55e',
    warning: '#f97316',
    danger: '#ef4444',
    border: '#e5e7eb',
    card: '#ffffff',
    fontFamily: 'Inter, Microsoft YaHei, sans-serif',
  },
  tech: {
    name: '科技',
    primary: '#0f172a',
    secondary: '#8b5cf6',
    background: '#0f172a',
    text: '#e2e8f0',
    textLight: '#94a3b8',
    textFaint: '#64748b',
    accent: '#06b6d4',
    success: '#10b981',
    warning: '#f59e0b',
    danger: '#ef4444',
    border: '#334155',
    card: '#1e293b',
    fontFamily: 'Inter, Microsoft YaHei, sans-serif',
  },
  education: {
    name: '教育',
    primary: '#7c3aed',
    secondary: '#f97316',
    background: '#ffffff',
    text: '#374151',
    textLight: '#6b7280',
    textFaint: '#9ca3af',
    accent: '#ec4899',
    success: '#10b981',
    warning: '#f59e0b',
    danger: '#ef4444',
    border: '#e5e7eb',
    card: '#ffffff',
    fontFamily: 'Inter, Microsoft YaHei, sans-serif',
  },
  creative: {
    name: '创意',
    primary: '#ec4899',
    secondary: '#06b6d4',
    background: '#ffffff',
    text: '#1f2937',
    textLight: '#6b7280',
    textFaint: '#9ca3af',
    accent: '#8b5cf6',
    success: '#22c55e',
    warning: '#f97316',
    danger: '#ef4444',
    border: '#e5e7eb',
    card: '#ffffff',
    fontFamily: 'Inter, Microsoft YaHei, sans-serif',
  },
  dark: {
    name: '暗黑',
    primary: '#111827',
    secondary: '#374151',
    background: '#0f172a',
    text: '#f9fafb',
    textLight: '#d1d5db',
    textFaint: '#9ca3af',
    accent: '#0ea5e9',
    success: '#22c55e',
    warning: '#f59e0b',
    danger: '#ef4444',
    border: '#374151',
    card: '#1f2937',
    fontFamily: 'Inter, Microsoft YaHei, sans-serif',
  },
};

export const getTheme = (theme: ThemeType): ThemeConfig => {
  return themes[theme];
};

export const themeList: ThemeType[] = ['business', 'tech', 'education', 'creative', 'dark'];