from __future__ import annotations

from pathlib import Path
import sys
from typing import Any, get_args, get_origin

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.core.prompt_context import PromptContextUsage
from app.core.llm_usage import ModelUsage
from app.schemas.agent_os import (
    AgentAnalysisResponse,
    AgentBoard,
    CapabilityExecutionAttempt,
    CapabilityExecutionMetadata,
    AgentGapDetail,
    AgentMission,
    AgentOSRequest,
    AgentRuntimeMetadata,
)


OUT = ROOT / "src" / "api" / "generated" / "agentOsContracts.ts"
MODELS = [
    AgentOSRequest,
    AgentMission,
    AgentGapDetail,
    AgentBoard,
    PromptContextUsage,
    ModelUsage,
    CapabilityExecutionAttempt,
    CapabilityExecutionMetadata,
    AgentRuntimeMetadata,
    AgentAnalysisResponse,
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render_contracts(), encoding="utf-8")


def render_contracts() -> str:
    lines = [
        "// Generated by scripts/generate_agent_os_contracts.py",
        "// Source of truth: app/schemas/agent_os.py",
        "",
    ]
    for model in MODELS:
        lines.append(render_interface(model))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_interface(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        marker = "?" if model is AgentOSRequest and not field.is_required() else ""
        lines.append(f"  {name}{marker}: {ts_type(field.annotation)};")
    lines.append("}")
    return "\n".join(lines)


def ts_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin is None:
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            return annotation.__name__
        return {
            str: "string",
            int: "number",
            float: "number",
            bool: "boolean",
            Any: "unknown",
        }.get(annotation, "unknown")

    if origin in (list,):
        inner = ts_type(args[0]) if args else "unknown"
        return f"{inner}[]"

    if origin in (dict,):
        value = ts_type(args[1]) if len(args) > 1 else "unknown"
        return f"Record<string, {value}>"

    if str(origin).endswith("Literal"):
        return " | ".join(repr(arg) for arg in args)

    if origin in (_union_type(),):
        non_null = [arg for arg in args if arg is not type(None)]
        rendered = " | ".join(ts_type(arg) for arg in non_null)
        return f"{rendered} | null" if len(non_null) != len(args) else rendered

    return "unknown"


def _union_type():
    return get_origin(str | None)


if __name__ == "__main__":
    main()
